### ISSUE TITLE
Dialyzer disabled because core Elixir modules are missing debug info

### ISSUE THREAD

**Issue by lleger** [JakeBecker/elixir-ls#113]
After upgrading to new Erlang / Elixir versions, I'm seeing a crash with Dialyzer. Screenshot attached.

<img width="469" alt="screen shot 2018-08-09 at 12 26 05 am" src="https://user-images.githubusercontent.com/52359/43879739-005fd50c-9b6b-11e8-954b-45033f036f9d.png">

FWIW, I don't see a manifest for OTP 21, but I'm not sure how to force the plugin to create one:

```
.elixir_ls
├── build
├── dialyzer_manifest_20.2.2_elixir-1.6.0_test
├── dialyzer_manifest_20.3_elixir-1.6.4_test
├── dialyzer_manifest_20_elixir-1.6.0_test
└── dialyzer_tmp
```

### Environment

* Elixir & Erlang versions (elixir --version): 1.7.2 / 21.0
* Operating system: macOS High Sierra
* Client (editor or IDE): VSCode

**Comment by JakeBecker** [comment]
Erlang/OTP 21's version of Dialyzer ended support for the OTP 19 style debug info chunk. Your version of Elixir was mostly compiled with OTP 19 and uses this legacy format for the debug info. I recommend using a tool like kiex to recompile Elixir now that you've upgraded to OTP 21.

**Comment by lleger** [comment]
That did the trick! For asdf users, specify the OTP version with the elixir version in your `.tool-versions` file like so:

```
erlang 21.0
elixir 1.7.2-otp-21
```

Then `asdf install` again and reopen VSCode.
