### ISSUE TITLE
The `import_deps` option in .formatter.exs is ignored

### ISSUE THREAD

**Issue by alco** [JakeBecker/elixir-ls#114]
### Environment

* Elixir & Erlang versions (elixir --version):
  
  ```
  Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

  Elixir 1.6.4 (compiled with OTP 19)
  ```

* Operating system: macOS
* Client (editor or IDE): VSCode  1.26.0

I've created a dummy project with `mix new fmt_test` and added `{:plug, "~> 1.0"}` in `mix.exs`. Contents of my `.formatter.exs` at the root of the project:

```
# Used by "mix format"
[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  import_deps: [:plug]
]
```

Contents of the `lib/fmt_test.ex` file:

```
defmodule FmtTest do
  use Plug.Builder

  plug :foobar

  def foobar(conn, _opts) do
    conn
  end
end
```

When I navigate to the project root in my shell and run `mix format`, it leaves the code unchanged. However, invoking the `Format document` command in VSCode changes the 4th line to `plug(:foobar)`.

I think this is related to the caveat mentioned in the docs for [mix format](https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-formatting-options):

> * `:import_deps` (a list of dependencies as atoms) - specifies a list of dependencies whose formatter configuration will be imported. **When specified, the formatter should run in the same directory as the `mix.exs` file that defines those dependencies**. See the “Importing dependencies configuration” section below for more information.

**Comment by JakeBecker** [comment]
This works if you're using Elixir >= 1.6.5. See https://github.com/JakeBecker/elixir-ls/issues/67

**Comment by alco** [comment]
Oops, sorry I missed that.
