### ISSUE TITLE
@spec suggestions don't show for functions with @doc attribute

### ISSUE THREAD

**Issue by tmepple** [JakeBecker/elixir-ls#115]
### Environment

* Elixir & Erlang versions: v1.7.2 - OTP 21
* Operating system: MacOS 10.13.6
* Client (editor or IDE): VSCode 1.26.0

The automatic `@spec` suggestions are awesome... only issue is they don't appear if there is a `@doc` on the function.  It's easy to workaround by commenting out the documentation, grabbing the `@spec`, then removing the comment but was wondering if it was easily fixable.

**Comment by eaverdeja** [comment]
Hey @JakeBecker! First of all, amazing extension! I've been learning Elixir for the past months and using this extension with VS Code definitely contributed to the positive experience. Thank you :tada: 

Sadly, the error reported happens to me using:

- Elixir 1.8.2
- Erlang 22
- VS Code 1.34.0

I can also confirm that commenting out the @doc block (using the `ctrl+k & ctrl+c` shortcut) and waiting for a few seconds makes the @spec suggestion appear. Uncommenting the @doc block (using the `ctrl+k & ctrl+u` shortcut) makes it pretty painless.

Unfortunately (in this specific context, obviously), a lot of the functions created when using Phoenix generators already come with @doc's out of the box. That makes it quite easy to "forget" or "ignore" the tedious process described above (especially tedious for generated stuff..)

Do you happen to have a fix and you just forgot to merge it :grin:?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
