### ISSUE TITLE
Using debugger outside of VS-Code

### ISSUE THREAD

**Issue by QuadeMorrison** [JakeBecker/elixir-ls#116]
I'm looking into writing an implementation of the debugging protocol, and I haven't been able to figure out how to communicate with your debugger.

When I run the debugger.sh I gather it wants input from me, but input such as 'Content-Length: 44\r\n\r\n{"type": "request", "command": "initialize"}' and similar variations doesn't seem to get me anywhere, despite working in several other debuggers I've tried.

`{"body":{"category":"stderr","output":"** (MatchError) no match of right hand side value: [\"Content-Length\", \"44\\\\r\\\\n\\\\r\\\\n{\\\"type\\\"\", \"\\\"request\\\", \\\"command\\\"\", \"\\\"initialize\\\"}\"]\n    (elixir_ls_utils) lib/packet_stream.ex:42: ElixirLS.Utils.PacketStream.read_header/2\n    (elixir_ls_utils) lib/packet_stream.ex:22: ElixirLS.Utils.PacketStream.read_packet/1\n    (elixir_ls_utils) lib/packet_stream.ex:12: anonymous fn/2 in ElixirLS.Utils.PacketStream.stream/1\n    (elixir) lib/stream.ex:1377: Stream.do_resource/5\n    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4\n    (elixir) lib/stream.ex:637: Stream.run/1\n    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6\n"},"event":"output","seq":2,"type":"event"}`

This is the error I get. I'm not an elixir person so I'm having a hard time deciphering what this means. I just want to be compatible with the current implementations of the protocol. Thanks.

**Comment by norpan** [comment]
It looks like you are sending the string with literal "\r" and "\n" in it. Those should be actual linefeed/newline characters.

If you are using bash or a similiar unix shell, you can try doing something like this:
printf 'Content-Length: 44\r\n\r\n{"type": "request", "command": "initialize"}' | ./debugger.sh

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
