### ISSUE TITLE
Find all references fails to find calling functions using default arguments

### ISSUE THREAD

**Issue by tmepple** [JakeBecker/elixir-ls#118]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.3 (compiled with Erlang/OTP 21)
* Operating system:  MacOS 10.13.6
* Client (editor or IDE):  VSCode 1.26.1

I frequently use default arguments in function heads such as `def update_password_changeset(%User{} = user \\ %User{}, params) do` which allows callers to submit a custom User struct for updating (arity 2) or callers can just submit the params (arity 1) which runs the validations against an empty User struct.

Unfortunately using `Find all References` on that function head only finds the callers that are using arity 2.

Looking at the code here: https://github.com/JakeBecker/elixir-ls/blob/1ef05b9958c23bbe9f928fc4f4774bd5acf1629d/apps/language_server/lib/language_server/providers/references.ex#L29 it looks like the code is detecting the arity at the cursor (in my example it would be 2) then basically runs `mix xref callers User.update_password_changeset/2` which gives no results.  If you would run `mix xref callers User.update_password_changeset` it gives the callers for all arities and if you run `mix xref callers User.update_password_changeset/1` it returns my caller using the default arguments.

If the code could detect default arguments are being used and the function head covers arity 1 and 2 I guess it could call `mix xref callers` for each arity and merge the results... or probably easier to call `mix xref callers` without arity to get every caller then filter out any caller using an arity other than 1 or 2.  I was looking into maybe making a PR but noticed this function is relying heavily on `ElixirSense` introspection which might be too complex for me or require changes in that repo... I can't tell if it takes default arguments into account.

I know I can work around this by never using default arguments and always create multiple function heads with different arities which supply the defaults but it would be great if it worked with default arguments also.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
