### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by Shados** [JakeBecker/elixir-ls#119]
Or, on the off chance I've become spectacularly (albeit selectively) blind: Can you document the license more clearly?

**Comment by kabo** [comment]
A very reasonable request, I'm also keen on knowing what the license for this project is.

**Comment by balduncle** [comment]
I have reached out to @JakeBecker to see if he is willing to merge the above PR and clear up any doubt about the license.  🤞

**Comment by balduncle** [comment]
The closest thing I can find to a license is this reference to MIT in vscode-elixir-ls.

https://github.com/JakeBecker/vscode-elixir-ls/blob/3f5bde06c23251a7a1eb5ef90ff3a60786efccc9/package.json#L12
