### ISSUE TITLE
Check that Dialyzer exists before attempting to use it

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#121]
Homebrew's `erlang` package does not include Dialyzer and causes a crash: https://github.com/JakeBecker/vscode-elixir-ls/issues/104#issuecomment-421251049

**Comment by jsimmonds2** [comment]
Hi,  #104 in vscode-elixir-ls was Ubuntu 18.04.1 LTS  not MacOS.  Thanks.   Also, it was ESL's plain `erlang` release of Erlang/OTP 21, for that Ubuntu (Bionic), which was missing `dialyzer`.
