### ISSUE TITLE
@spec suggestions not appearing for defp

### ISSUE THREAD

**Issue by TheFirstAvenger** [JakeBecker/elixir-ls#123]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.3/21
* Operating system: MacOS High Sierra
* Client (editor or IDE): VSCode

Probably should be an option you could enable, but would like the ability to show @spec suggestions for defp and not just def.

**Comment by JakeBecker** [comment]
Unfortunately, Dialyzer doesn't make this easy to do. Dialyzer keeps a data structure called the PLT ("Persistent Lookup Table") with the results of its analysis, it's what gets saved to disk if you save a PLT file. The PLT includes the inferred success typings for public functions but not for private ones, and so getting those success typings would require more mucking around in Dialyzer's guts than I'm willing to put in. Also, I think @spec annotations on private functions aren't even allowed in Elixir. I'm going to consider this a "wontfix" unless someone volunteers to try it :)

**Comment by TheFirstAvenger** [comment]
@JakeBecker I found myself renaming a `defp` to `def` temporarily to get a spec to appear, applying it, then returning it to `defp`. I wonder if that would be the route to take to get these to appear? i.e. If a flag is set to request specs on defp, then make a copy of the codebase with all `defp`'s set to `def`, and key any `defp` spec suggestions off that copy.

**Comment by OvermindDL1** [comment]
Elixir-LS could always set the compiler option (environment variable or passed via the mix.exs file or so) to compile private functions as public.  You will lose the 'unused function' error at that point but you will gain full dialyzation on them.  Maybe two environments, one of everything public and one of everything not and just merge non-identical errors?
