### ISSUE TITLE
Endless compiling in umbrella project

### ISSUE THREAD

**Issue by outsmartin** [JakeBecker/elixir-ls#128]
### Environment

* Elixir & Erlang versions (elixir --version):
Elixir version: "1.7.3 (compiled with Erlang/OTP 21)"
Erlang version: "21"

* Operating system: MacOS Mojave
* Client (editor or IDE): VSCode 

### Problem description
```
Started ElixirLS
Elixir version: "1.7.3 (compiled with Erlang/OTP 21)"
Erlang version: "21"
Compiling with Mix env dev
==> consignment_api
Compiling 6 files (.ex)
[Info  - 11:59:06 AM] Compile took 2178 milliseconds
Compiling with Mix env dev
[Info  - 11:59:06 AM] Compile took 372 milliseconds
Compiling with Mix env dev
[Info  - 11:59:07 AM] Compile took 345 milliseconds
Compiling with Mix env dev
```

Afterwards it never stops compiling. I don't know how to further debug it. I tried cleaning the dependencies. It only happens in one of the umbrella applications we work on. The normal phoenix app I also work on works as expected.

I would be glad for any advice how to dig deeper.
Thank you very much.

**Comment by outsmartin** [comment]
I found the culprit, we had a 
```
build_embedded: true
```

in our main mix.exs file.
I changed it to

```
build_embedded: Mix.env() == :prod
```

now it works.

Not sure if this is expected but I'm happy again :shipit:

**Comment by JakeBecker** [comment]
Interesting, I hadn't known about that quirk. Usually the culprit is a custom Mix compiler that generates new source files which triggers a recompilation. I'll have to look into why this happens. Glad you discovered this!
