### ISSUE TITLE
Format on save does not use the `inputs` section of .formatter.exs file

### ISSUE THREAD

**Issue by skateinmars** [JakeBecker/elixir-ls#129]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.5, Erlang/OTP 21
* Operating system: Ubuntu 17.10
* Client (editor or IDE): Visual Studio Code 1.28.2

### Report

The inputs section of a formatter configuration file determines to which files the `mix format` task should apply formatting.
The language server uses this file to apply options such as `locals_without_parens`, but it does not take into account the inputs configuration and applies formatting to any elixir file.

Steps to reproduce:
* Clone JakeBecker/elixir-ls
* Go into the project directory and run `echo "IO.inspect 4" > new.exs`
* Run `mix format` and confirm that the new.exs file did not change
* Start vscode within the elixir-ls folder
* Open new.exs and run the save command
* => The file gets formatted

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
