### ISSUE TITLE
Heredoc resulting in warnings from elixir-ls

### ISSUE THREAD

**Issue by zachdaniel** [JakeBecker/elixir-ls#130]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.3
* Operating system: OSX
* Client (editor or IDE): Emacs

1.  If using a client other than VS Code, please try VS Code's ElixirLS extension. Does it reproduce your failure?

Yes, but the symptom's aren't as bad because VSCode hides the output, whereas the emacs messages buffer is more obvious/annoying.

2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.

Issue is reproducable in an empty project.

3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)

This is getting spammed constantly when navigating in heredocs

```
[Warn  - 3:11:45 PM] warning: outdented heredoc line. The contents inside the heredoc should be indented at the same level as the closing """. The following is forbidden:

    def text do
      """
    contents
      """
    end

Instead make sure the contents are indented as much as the heredoc closing:

    def text do
      """
      contents
      """
    end

The current heredoc line is indented too little
  nofile:39
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
