### ISSUE TITLE
Ignore Dialyzer warnings from deps

### ISSUE THREAD

**Issue by hisapy** [JakeBecker/elixir-ls#131]
This is more like a feature request. 

Currently, Elixir LS is reporting warnings on my files on line 1, but all of them are actually coming from deps. I wonder if it's possible to ignore those warnings in order to avoid noise and focus only on warnings/errors of my own source code.

Thanks in advance.

**Comment by hauleth** [comment]
This would be infeasible to ignore *all* warnings from deps. Instead I would suggest you to configure Dialyzer to ignore these errors you are seeing. Or mention them to the dependency authors that they have dialyzer errors in their macros.

**Comment by hisapy** [comment]
Well, I've tried to ignore warnings via Dialyzer Warn Opts in Elixir LS settings but I couldn't achieve what I wanted.

* I don't want to ignore warnings from my own code.
* I know all of the warnings not specifically related to my code are on line 1 (`defmodule`) so I tried to ignore any warning on line 1, without success
* I also tried to use `@dialyzer` module attribute to achieve something similar without success.

I'll leave this issue open in case I or someone comes up with ideas...

**Comment by Nitrino** [comment]
Once compiled, dependencies become part of your application and should be considered in line with your code.
If you want to disable specific errors or exclude files, use `.dialyzer_ignore.exs`
https://github.com/jeremyjh/dialyxir#ignore-warnings

**Comment by hisapy** [comment]
If I'm not wrong, the Dialyzer from ElixirLS is not related to dialyxir ... I don't even have Dialyzer in my mix.exs

**Comment by laibulle** [comment]
@Nitrino I have a `.dialyzer_ignore.exs` wich work just find with `mix dialyzer` but it is totally ignored by `elixir-ls`

**Comment by Signez** [comment]
It would be really useful to be able to rely on `dialyxir` (and the configuration from `mix.exs`), so that the return of _ElixirLS_ would mimic the result of `mix dialyxir`. It is very confusing right now, I just passed a working day on trying to understand how to silence a warning on a file – only to give up… 😥

**Comment by pietrofxq** [comment]
+1 for this feature. I have a project with Phoenix and ElixirLS complains about some functions that are generated at runtime (Routers.{controller_name}_path). Dialyzer does not complain about them, but there's no way for me to make ElixirLS remove these warnings.

**Comment by kiere** [comment]
@pietrofxq I will have a similar problem where I may generate some code using a certain route and then decide to nest it our change the `as` option.  ElixirLS will then continue to show warnings about calls to the old route name.  I've have performed a find-in-project and it definitely is not there.  The error I see always follows this pattern...

```
Call to missing or unexported function 'Elixir.MyAppWeb.Router.Helpers':some_old_path/2
```

I cannot figure out how to clear it.  I tried wiping out the `_build` and `.elixir_ls` directories in case some lingering compiled code was hanging around (and restarting VS Code after all that).   Nothing works.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
