### ISSUE TITLE
Is it possible to disable dialyzer in vim/ALE?

### ISSUE THREAD

**Issue by jschomay** [JakeBecker/elixir-ls#133]
Apologies if this is an annoying noob question.

I'm using this as a linter in ALE for vim as noted in the docs, and it works great.  However, on a larger project it runs up my CPU and computer's fans on saves.

I have seen other similar issues with the suggestion to set `elixirLS.dialyzerEnabled` to false.  I am not sure how to do that, or if that is possible with the vim/ALE integration.  Do you know the answer to that, or should I ask on https://github.com/w0rp/ale (@jparise did the integration there - w0rp/ale#1956)?

Thank you so much!

**Comment by jparise** [comment]
I’m happy to update the ALE integration based on whatever we can figure out here.

**Comment by jparise** [comment]
I think I have something working now. I just needed to add the ability to pass LSP initialization options. I'll add some documentation and submit an ALE pull request later today or tomorrow (and update this issue accordingly).

Thanks for pointing this out, @jschomay!

**Comment by JakeBecker** [comment]
Dialyzer is the culprit for this like 95% of the time. If you let it run for a while (potentially a long time on slower machines) it might finish generating a PLT file with saved analysis for common Elixir modules and then things will improve, but disabling Dialyzer is a good idea if it's not finishing in a reasonable amount of time.

Since this is mostly an issue with the client (vim/ALE), I'm going to close this issue and let it be tracked over there instead.

**Comment by jschomay** [comment]
Thanks.  What you said is correct, there was definitely a hit at the beginning, and now it isn't so bad, though it still gets a CPU spike when ever there is a compile error.  I'm not sure, but setting my ALE linters to just use elixir-ls (and not also credo, etc) might have also helped.

I think part of the problem initially was that in an umbrella project, it was building a PTL/elixir-ls in each app's directory, so it was working overtime.  I have also noticed that if I lint code that uses a module in an app that hasn't had the PTL generated yet, it will kick it off then, which might be unexpected.

**Comment by JakeBecker** [comment]
You should get one primary PLT file in `~/.mix` and then a dialyzer manifest file in the project root `.elixir_ls/`. Once these are built, it will re-analyze modules only when they or their references change, but this will still spike CPU each time (though usually not for more than a few seconds on good machines). Disable it if you're in a slower machine or it's annoying you.

**Comment by jparise** [comment]
w0rp/ale#2042 provides the configuration framework necessary to support disabling Dialyzer (and specific any other configuration settings).

**Comment by jschomay** [comment]
@JakeBecker I am seeing a .elixir_ls/ in each app of my umbrella project, rather than one at the top level.  Is that expected, or is that worth looking into further?

**Comment by jparise** [comment]
@jschomay see w0rp/ale#2045 for umbrella project support.

**Comment by jschomay** [comment]
You are on top of it @jparise!  Thank you.

**Comment by schnittchen** [comment]
Am I getting this config right?

```
let g:ale_elixir_elixir_ls_config = { 
\   'elixirLS': {
\     'dialyzerEnabled': v:false,
\   },  
\}
```

Because I still have high CPU usage for a very long time, and there is a `.elixir_ls/dialyzer_tmp/` as well.

**Comment by Stratus3D** [comment]
I've got the same question as @schnittchen. My config looks like what is shown in the docs. Maybe I should just disable elixirLS altogether?

**Comment by schnittchen** [comment]
@Stratus3D ale used to ignore the config due to a bug, see https://github.com/w0rp/ale/issues/2397#issuecomment-479196385
