### ISSUE TITLE
Support initialize.initializationOptions

### ISSUE THREAD

**Issue by jparise** [JakeBecker/elixir-ls#134]
In investigating #133, I noticed that ElixirLS only uses the `workspace/didChangeConfiguration` message to control settings. The `initialize` request also supports `initializationOptions`, however, and I wonder if that might be a more appropriate place to control things like `dialyzerEnabled`, which are really only meaningful at initialization time.

See: https://microsoft.github.io/language-server-protocol/specification#initialize

One backwards-compatible approach would be to honor `initializationOptions` for the initial settings and let `workspace/didChangeConfiguration` continue to update them.

I discovered this specifically because ALE (for Vim) currently has better support for passing initialization options than "configuration change" messages, but addressing that is of course an unrelated thing.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
