### ISSUE TITLE
add auto import and use shortcut when input some module name

### ISSUE THREAD

**Issue by LoranceChen** [JakeBecker/elixir-ls#135]
I like the way elixir language and beam. As a Java developer in work, I really enjoy the way of auto import class path in Java IDE. In elixir, such as:
1. had define a module named `Myproject.MyModuleA`.
2. If I'm input `MyModuleA.use` in another module named `ModuleB`, the IDE could give me a choice to generate a `use MyProject.MyModuleA` at top of the module `ModuleB`.
Similarly, If input `MyModuleA.import`, the IDE could generate `import MyProject.MyModuleA`.

There a many of detail to handle auto import/use, but that is a first important things  todo.  

I hope I can do this feature, but I'm not familiar with the project and LSP.  

I'm sure the feature will bring elixir to another step!  

Thanks for the great project.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
