### ISSUE TITLE
No definition for core modules in VSCode

### ISSUE THREAD

**Issue by strychnide** [JakeBecker/elixir-ls#136]
### Environment

* Elixir & Erlang versions (elixir --version): elixir 1.7.4 from kiex, erlang 21.x OTP
* Operating system: Linux
* Client (editor or IDE):VSCode

1.  If using a client other than VS Code, please try VS Code's ElixirLS extension. Does it reproduce your failure?
 Already using VSCode
2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it. 
Yes, reproducible on empty project (on my machine at least)
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.) 
Log appears => server launched
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
No errors there.

As title says, no definition for core modules (F12), both when elixir is installed by kiex and by the package manager.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
