### ISSUE TITLE
Does elixir-ls need to be compiled with same Elixir and Erlang version as your project?

### ISSUE THREAD

**Issue by mhanberg** [JakeBecker/elixir-ls#137]
### Environment

* Elixir & Erlang versions (elixir --version): N/A
* Operating system: macOS
* Client (editor or IDE): MacVim, ALE

I am building elixir-ls from source, and I noticed that it only seems to work if I compiled it with the same elixir and Erlang versions as the current project is using. 

ALE logs and `ps aux | grep 'elixir'` show that the server has started, but it doesn't seem to work until I recompile it with the appropriate versions.

I feel like this shouldn't be the case, as you don't have control over this when using the VSCode extension. 

Thanks!

cc/ @jparise

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
