### ISSUE TITLE
Syntax Highlight parser for local variables and parameters

### ISSUE THREAD

**Issue by silva96** [JakeBecker/elixir-ls#142]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 21 [erts-10.0.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Operating system: 
```
MacOS Sierra
10.12.6
```
* Client (editor or IDE): `VS Code`

### Feature request / Doubt

How can we achieve this behaviour on highlighting?  (IntelliJ IDEA)

![image](https://user-images.githubusercontent.com/4019924/50490554-7288a380-09ec-11e9-9f05-c4dc8325e9b6.png)

Currently in VS Code It doesn't highlight variables

![image](https://user-images.githubusercontent.com/4019924/50490573-8c29eb00-09ec-11e9-9e67-e8b2ced335f9.png)

**Comment by OvermindDL1** [comment]
For note, that's generally called Rainbow Highlighting, I have a plugin in Atom that does that so I'd expect VSCode does too.

**Comment by silva96** [comment]
Didn't find it in vscode

**Comment by OvermindDL1** [comment]
@silva96 Sounds like you should make a new extension then.  :-)

It works very well in Atom though if you want to try it there (and atom is about on par with VSCode in speed now since its overhauls in the past year, with significantly more extensions and features).

**Comment by silva96** [comment]
I couldn't find it in atom neither, can you provide a link please?

**Comment by OvermindDL1** [comment]
@silva96 There's a couple out there but I use https://atom.io/packages/semanticolor as you can fine-tune colorization on lots of different parsed token types.  I have variables set to 'colorize' (rainbow mode) for example with comments set as 'contrast' (I like them being really visible), support types as 'colorize', etc... etc...

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
