### ISSUE TITLE
Any way to disable dialyzer popups in SublimeText?

### ISSUE THREAD

**Issue by sardaukar** [JakeBecker/elixir-ls#147]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: macOS Mojave 10.14.2
* Client (editor or IDE): SublimeText 3

Not sure if this is the right place, but I'm using `elixir-ls` with https://github.com/tomv564/LSP and I get a dialyzer popup every single time I save a file, which is a bit much. I tried having a `settings.json` file with 

```
{
    "elixirLS": {
      "dialyzerEnabled": false
    }
}
```

but no show. Is this a LSP problem? The popup says `ElixirLS Dialyzer` on every line. Thanks for any help!

**Comment by sardaukar** [comment]
Found it, nevermind!

**Comment by lessless** [comment]
@sardaukar how did you do that?

**Comment by sardaukar** [comment]
Sorry, don't even use Sublime anymore :|

**Comment by rockerBOO** [comment]
In your Package Settings > LSP > Server > LSP-Elixir, modify your user settings. 

~/.config/sublime-text-3/Packages/User/LSP-elixir.sublime-settings
```
// Settings in here override those in "LSP-elixir/LSP-elixir.sublime-settings",
{
	"settings": {
		"elixirLS": {
			// Run ElixirLS's rapid Dialyzer when code is saved
			"dialyzerEnabled": false,
		}
	}
}
```

**Comment by lessless** [comment]
@rockerBOO I don't have `Server` section  under `LSP` in `Package Settings`. Do I need to install an additional package to see it there?
