### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by kiurchv** [JakeBecker/elixir-ls#149]
I think it will be great to have the ability to install elixir-ls from Homebrew so that I've created a PR with elixir-ls formula to homebrew-core.

Anyone who wants to see elixir-ls on Homebrew, please support my PR: Homebrew/homebrew-core#35918

Thanks!

**Comment by qgadrian** [comment]
@kiurchv the PR is closed, will you push for it?

**Comment by kiurchv** [comment]
I can submit the new PR if this issue gain enough support

**Comment by kiurchv** [comment]
An another attempt is happening at Homebrew/homebrew-core#44105
Show your support, please!

**Comment by filalex77** [comment]
@kiurchv Thanks for starting the effort! I hope nothing impedes this from being merged now :)

**Comment by pavloo** [comment]
Sorry for flood, but let's get this merged, guys!

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
