### ISSUE TITLE
Environment variables not loaded.

### ISSUE THREAD

**Issue by jfreeze** [JakeBecker/elixir-ls#15]
This project compiles the project in the background, but does not have access to environment variables. When running the project in an environment with env vars set, they are not picked up because the project has already been compiled by the editor.

Recommended change is for this project to compile in an isolated area that does not affect the main _build dir.

Simple test.

$ export var="foo"

defmodule MyApp do
  @var Application.get_env(:my_app, :var)
  def var, do: @var
end

Touching the above file and running iex -S mix will not invoke a compile, and the @var will be nil, because the project is compiled in the background before iex -S mix can be run and that env does not have the right environment variable.

**Comment by hauleth** [comment]
`Application.get_env/2` doesn't use system environment variables but uses `sys.conf`. You need to clarify what you want.

**Comment by jfreeze** [comment]
I created a simple test project as follows:

config/config.exs ------

use Mix.Config
config :get_env_test,
  var: System.get_env("var")

lib/get_env_test.ex --------

defmodule GetEnvTest do
  @var Application.get_env(:get_env_test, :var)

  def test do
    IO.puts("@var = '#{@var}'")
  end

end

--------

You can run the test as follows:

1. Enable ElixirLS Extension
2. Modify the project and save it to force a recompile.
3. From the terminal, run:  var="fred" iex -S mix
4. From iex run: 
iex(1)> GetEnvTest.test
@var = ''

----
To make the bug go away, do the following:
1. Disable ElixirLS Extension
2. Reload VS Code
3. Modify the project to force a recompile
4. From the terminal, run:  var="fred" iex -S mix
4. From iex run: 
iex(1)> GetEnvTest.test
@var = 'fred'

My assumption is that the following is happening:
The @var in GetEnvTest module is being set during compile time. When ElixiLS is running, it compiles the project (without the env var being set) and hence the test fails. The confusion is caused when a developer sets the env var and runs the code, but @var is never set because the project has already been compiled by ElixirLS with an invalid env. The developer must know to force a compile before debugging when using ElixirLS.

Is there a way to run ElixirLS in its own build environment so that it does not affect the development environment?

**Comment by JakeBecker** [comment]
VS Code should load your shell's environment variables when it's launched. If those environment variables affect compilation, then you'll have to recompile after changing them. That's true whether you use ElixirLS or run `mix compile` from the CLI.

I'm planning to add a setting to override which `MIX_ENV` is used when building your project, so if you wanted, you could set up a custom env just for the IDE. That should give you more flexibility if you need it. I'm going to close this issue because I don't plan to change the way environment variables are handled for now.
