### ISSUE TITLE
Second format adds extra empty line

### ISSUE THREAD

**Issue by wanton7** [JakeBecker/elixir-ls#152]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Operating system: Windows 10 (64-bit)
* Client (editor or IDE): (Visual Studio Code 1.31.1) ElixirLS (0.2.24)

Second format (Shift+Alt+F on Windows) of Elixir code (.ex) adds extra empty line. Third format doesn't add more empty lines. It seems to only happen with CRLF line ending

Before format
![elixir_before_format](https://user-images.githubusercontent.com/1009930/53168617-be6a5a00-35e3-11e9-8fa7-1f7b8a553f66.png)

After format
![elixir_after_format](https://user-images.githubusercontent.com/1009930/53168636-c9bd8580-35e3-11e9-8f62-b0b7b7e2f765.png)

After second format
![elixir_after_second_format](https://user-images.githubusercontent.com/1009930/53168641-cfb36680-35e3-11e9-8f5b-cdfef72f3897.png)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
