### ISSUE TITLE
"Skipping build" on Windows\WSL and in other case

### ISSUE THREAD

**Issue by vheathen** [JakeBecker/elixir-ls#153]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating system:
Windows + WSL

* Client (editor or IDE):
VS Code

I'm facing the same problem as in #34 but in native Windows VS Code + WSL Elixir subsystem. It is possible to run all erlang\elixir staff within WSL, but then I get a message like this:

```
Skipping build because cwd changed from /c:/cloud/Documents/Projects/some_project to /mnt/c/cloud/Documents/Projects/some_project.
```

Dialyzer build works fine though.

At the same time I've found that if I open a project in VS Code/Ubuntu from the link (f.e., I have a link from /home/vlad/Projects to /mnt/c/cloud/Documents/Projects) then I get the same skipping build problem:

```
Skipping build because cwd changed from /home/vlad/Projects/some_project to /mnt/c/cloud/Documents/Projects/some_project.
```

I've made a simple patch to check paths translated from '/c:/path' to '/mnt/c/path'. It works fine with Ubuntu native VSCode as well. I don't have native Windows Elixir env so can't check against it but I believe it should work too. But this patch can't solve the second issue.

**Comment by vheathen** [comment]
The better way is to edit /etc/wsl.conf:
```
[automount]
root = /
options = "metadata"
```
and reboot computer (or at least WSL subsystem).

After that drives will bind to /drive (like /c for drive C:) and no need for any source updates.

I'm closing my PR now.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
