### ISSUE TITLE
Couldn't start client ElixirLS

### ISSUE THREAD

**Issue by daviwesley** [JakeBecker/elixir-ls#156]
#### Elixir
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)

#### Operating System
Linux elementary 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
#### VS Code
Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-36-generic

### Crash report template

After installing ElixirLS: Elixir support and debugger and opening a Phoenix project I got this error, this is the output error below

[Error - 21:46:21] Starting client failed
Launching server using command /home/elementary/.vscode/extensions/jakebecker.elixir-ls-0.2.24/elixir-ls-release/language_server.sh failed.

**Comment by daviwesley** [comment]
Mysteriously after reinstalling the problem disappeared

**Comment by JakeBecker** [comment]
I've seen occasional reports of the executable bit not being set on the launch scripts. I don't know why it happens, but that could maybe have been the cause. Feel free to re-open this issue if you can reproduce it.
