### ISSUE TITLE
Lint failed tests

### ISSUE THREAD

**Issue by TheFirstAvenger** [JakeBecker/elixir-ls#164]
Is it possible to read the failures out of `_build/test/lib/app_name/.mix/.mix_test_failures`, possibly using this call:
https://github.com/elixir-lang/elixir/blob/4da4ccdb8c6da13ea8b74fc79406878b455421ff/lib/ex_unit/lib/ex_unit/filters.ex#L123

and lint on the failed tests?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
