### ISSUE TITLE
Already compiled dependencies are recompiled in language server

### ISSUE THREAD

**Issue by arijoon** [JakeBecker/elixir-ls#170]
### Environment

* Elixir & Erlang versions (elixir --version): IEx 1.8.2 (compiled with Erlang/OTP 20) 
* Operating system: Windows
* Client (editor or IDE): Visual studio Code v1.35.1

Language server keeps re-compiling a project dependency even though it has been compiled in a separate shell (restarting the IDE LS does not fix it, also tried closing all LS and clean/get/compiling).

The issue is that for my example  `bcrypt_elixir`, I do not have build tools in path and do not wish to put them in my path (path will grow larger than limit). I have compiled this dependency in a separate window and then running VScode will cause this error

```
8:24:00.390 [error] Process #PID<0.222.0> raised an exception
** (Mix.Error) "nmake" not found in the path. If you have set the MAKE environment variable,
...
```

I understand the cause of error, however this dep is already compiled in another shell before even opening the IDE

```
Compiling 3 files (.ex)
Generated bcrypt_elixir app
```

Is there a setting to completely disable automatic compilation of dependencies by the language server and keep them fully manual?

**Comment by arijoon** [comment]
Just as a workaround for now I added the build tools to a new vscode launcher (i.e. just a bat file):
```bat
@echo off
REM Start VS Code with build tools

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

REM Start VS Code with command line arguments

start "" "C:\Program Files\Microsoft VS Code\Code.exe" %*
exit
```
![context menu](https://imgur.com/download/65SE8tm/)
and added another option to open it with build tools, it would be nicer if we could disable the auto compiling though.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
