### ISSUE TITLE
Poncho App Support

### ISSUE THREAD

**Issue by TylerPachal** [JakeBecker/elixir-ls#177]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.8.1 (compiled with Erlang/OTP 20)
* Operating system: MacOSX
* Client (editor or IDE): VSCode

### Description

`elixir-ls` has an option to specify a non-root project directory via the `elixirLS.projectDir` option.  However this is limited to a single mix project.  This is problematic for poncho-style projects where there are multiple mix projects that need to be compiled and built.

For example, I have a poncho project with two apps, and would like them both to be watched by `elixir-ls`:
```
api/
  mix.exs
consumer/
  mix.exs
```

### Possible Solution

I took a look at the code and think that adding a new option that accepts a list of path to poncho projects then starting a new `ElixirLS.LanguageServer.Server` instance for each one might be a good way forward here.

```"elixirLs.ponchoApps": ["api", "consumer"]```

I could try to make this change, unless folks can thing of an alternate approach.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
