### ISSUE TITLE
Outline doesn't seem to support describe blocks in test files

### ISSUE THREAD

**Issue by optikfluffel** [JakeBecker/elixir-ls#178]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system: macOS 10.14.5
* Client (editor or IDE): VSCodium 1.36.1

### Problem

Given a test file like:

```elixir
defmodule TestyMcTestfaceWeb.PageControllerTest do
  use TestyMcTestfaceWeb.ConnCase

  test "GET / does x", %{conn: conn} do
    # ...
  end

  test "GET / does y", %{conn: conn} do
    # ...
  end
end
```

the Outline works as expected:

![Screenshot 2019-07-20 at 10 33 02](https://user-images.githubusercontent.com/379915/61576386-d33b1300-aad9-11e9-8a5d-8e875edfb82b.png)

But when you group those tests in a `describe` block:

```elixir
defmodule TestyMcTestfaceWeb.PageControllerTest do
  use TestyMcTestfaceWeb.ConnCase

  describe "GET /" do
    test "does x", %{conn: conn} do
      # ...
    end

    test "does y", %{conn: conn} do
      # ...
    end
  end
end
```

the Outline becomes empty and doesn't show anything:

![Screenshot 2019-07-20 at 10 36 58](https://user-images.githubusercontent.com/379915/61576441-72f8a100-aada-11e9-8576-c5c6c3e5b754.png)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
