### ISSUE TITLE
Extract method refactoring

### ISSUE THREAD

**Issue by kevinkjt2000** [JakeBecker/elixir-ls#179]
Thanks for the implementation of LSP for Elixir!

I was noticing that in the specification of LSP there is mention of refactoring actions https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction
Is "extract method" on the roadmap for this implementation? Would a PR be welcome for this? If so, any pointers for a newbie? :)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
