### ISSUE TITLE
How to disable the default completion?

### ISSUE THREAD

**Issue by scottming** [JakeBecker/elixir-ls#180]
I'm using the [TabNine - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode) for completion, can I disable the elixir-ls default completion? I didn't found the config.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
