### ISSUE TITLE
** (ArgumentError) argument error when using "projectDir" setting

### ISSUE THREAD

**Issue by jtrees** [JakeBecker/elixir-ls#181]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.9.0 (compiled with Erlang/OTP 22)
```
* Operating system: elementary OS 5.0 [based on Ubuntu 18.04]
* Client (editor or IDE): Sublime Text with LSP plugin

### Description

I can get this LSP server working nicely with Sublime Text but it all breaks apart when I use the `projectDir` option. I have a project in subdir `phxapp` and get the following error when I open the project in my editor:

```
** (ArgumentError) argument error
    :erlang.binary_to_integer(nil)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:240: :erl_eval.expr/5
    (stdlib) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib) erl_eval.erl:233: :erl_eval.expr/5
    (stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:411: :erl_eval.expr/5
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
