### ISSUE TITLE
Is it possible to show errors and warnings for .exs files as well?

### ISSUE THREAD

**Issue by x-ji** [JakeBecker/elixir-ls#184]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.8.2 (compiled with Erlang/OTP 21)
* Operating system: MacOS
* Client (editor or IDE): VSCode

Sorry if this question has been asked before or if it's obvious. I haven't been able to find something similar when searching through the issues.

When using VSCode, `.ex` files are automatically linted and errors are shown on the fly, which is great for development. However, for `.exs` files, e.g. when I'm writing tests, errors will not be discovered until I actually run the `.exs` scripts. Is there a way for `elixir-ls` to also somehow try to compile them on the fly and show the errors?

I saw that there's a section in the README about *debugging* `.exs` files though this seems to be a different scenario.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
