### ISSUE TITLE
Add nested outline view

### ISSUE THREAD

**Issue by ridho9** [JakeBecker/elixir-ls#188]
The currently available document symbol provider only returns the symbols for all modules and their functions in flat manner. It would be nice if we could have it nested like other language servers.

**Comment by kent-medin** [comment]
![Screenshot_2019-08-31_14-29-58](https://user-images.githubusercontent.com/50149850/64063959-e7575180-cbfb-11e9-940b-7365219dec4b.png)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
