### ISSUE TITLE
Support textDocument/references

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#19]
Documented here: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_references

**Comment by balduncle** [comment]
I'm starting to looking into this at https://github.com/balduncle/elixir-ls/tree/balduncle-references.

**Comment by mattbaker** [comment]
@jakebecker - think this is closable now that we have the umbrella support in?

**Comment by JakeBecker** [comment]
Yep! I'll put together a release with the new features shortly.

**Comment by mattbaker** [comment]
Woo!

**Comment by JakeBecker** [comment]
It's live! Thanks for all the work you put in on this @mattbaker ❤️ 💚 💙 💛 💜

**Comment by mattbaker** [comment]
Awesome! And thank _you_, ElixirLS is great, and you've made it very easy to contribute to 💯
