### ISSUE TITLE
Formatter: Unknown dependency ... in the formatter configuration

### ISSUE THREAD

**Issue by djthread** [JakeBecker/elixir-ls#191]
### Environment

* Elixir 1.9.1, Erlang/OTP 22
* macOS 10.14.6
* VSCodium 1.38.1

### Issue

I seem to be having some trouble running the formatter, whether from the command palette or via alt+shift+f.

It works if I use it on a file generated with `mix new foo`, but if I try on a file generated with `mix phx.new foo`, nothing happens except I get this error in the ElixirLS output:

```
18:09:27.999 [error] Process #PID<0.111.0> raised an exception
** (Mix.Error) Unknown dependency :ecto_sql given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :test
    (mix) lib/mix.ex:389: Mix.raise/1
    (mix) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2
    (mix) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eval_deps_and_subdirectories/4
    (mix) lib/mix/tasks/format.ex:276: anonymous fn/2 in Mix.Tasks.Format.eval_subs_opts/3
    (elixir) lib/enum.ex:1087: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir) lib/enum.ex:3325: Enumerable.List.reduce/3
```

I've got no other apparent feedback. Also, it's interesting that I don't seem to get the `.elixir_ls` directory created in my project root.

What else might I check on? Any suggestions welcome!

### Related Issue, Maybe

https://github.com/elixir-editors/emacs-elixir/issues/415

**Comment by andersonmcook** [comment]
<img width="929" alt="Screen Shot 2019-10-03 at 12 07 45 PM" src="https://user-images.githubusercontent.com/8899069/66148486-a2498500-e5d6-11e9-962b-4230641dda4c.png">

what's your ElixirLS config look like? this is mine

**Comment by andersonmcook** [comment]
<img width="723" alt="Screen Shot 2019-10-03 at 12 10 05 PM" src="https://user-images.githubusercontent.com/8899069/66148539-c1e0ad80-e5d6-11e9-9956-b6373f9fcd40.png">

i also have this, whatever it may be

**Comment by djthread** [comment]
Hallelujah!

I wouldn't have thought since it seems to refer to behavior "on save", but checking this option

1. Got me my `.elixir_ls` directory
2. Made VSCode's formatter feature work

Thank you, @andersonmcook !

```
Elixir LS: Dialyzer Enabled
Run ElixirLS's rapid Dialyzer when code is saved
```
