### ISSUE TITLE
Idea: put a .gitignore in the .elixir_ls folder

### ISSUE THREAD

**Issue by mikl** [JakeBecker/elixir-ls#193]
Just a small idea: when creating the `.elixir_ls` folder, add a `.gitignore` file inside it with this content:

```
*
```

Given that almost everyone uses Git and no one (presumably) wants to add their `.elixir_ls` folder to their Git history, it would save users from having to set up an ignore rule themselves.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!

**Comment by JakeBecker** [comment]
That said... this is a good idea :)
