### ISSUE TITLE
Using elixir-ls on a network mount

### ISSUE THREAD

**Issue by joshio1** [JakeBecker/elixir-ls#199]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.4 and OTP 19
* Operating system: MAC
* Client (editor or IDE): VSCode

Is there any way of using this extension with VS code on a network mount. i.e. I have a shared folder between my VM on AWS and my local laptop. I want to view the code via VS Code on my laptop and use this extension primarily for go-to-definition and auto completion. Is there any way to accomplish this?

I am facing this issue because elixir-ls also compiles my phoenix code which clashes with the build directory when my code is compiled on the Ubuntu VM. i.e. I want my phoenix server to run on the VM. 

However, I would like to view the code from my laptop and use the go-to-definition and auto completion features using elixir-ls VS Code extension on my laptop. 

Please let me know if this is possible.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
