### ISSUE TITLE
ElixirLS RuntimeError Emacs

### ISSUE THREAD

**Issue by oolonc** [JakeBecker/elixir-ls#200]
```Started ElixirLS debugger
Elixir version: "1.9.2 (compiled with Erlang/OTP 22)"
Erlang version: "22"
(Debugger) Initialization failed because an exception was raised:
    ** (RuntimeError) could not lookup Ecto repo MrProject.Repo because it was not started or it does not exist
        Elixir.Ecto.Repo.Registry.erl:19: Ecto.Repo.Registry.lookup/1
        Elixir.Ecto.Adapter.erl:127: Ecto.Adapter.lookup_meta/1
        Elixir.Ecto.Adapters.SQL.Sandbox.erl:487: Ecto.Adapters.SQL.Sandbox.lookup_meta!/1
        Elixir.Ecto.Adapters.SQL.Sandbox.erl:388: Ecto.Adapters.SQL.Sandbox.mode/2
```

Debugger dies and complains Ecto repo could not be found in Emacs 26.3 and ecto_sql 3.2.1

**Comment by azazel75** [comment]
I'm stuck on a similar issues, has this been fixed by the  linked commit?

**Comment by axelson** [comment]
@azazel75 can you please retry, but ensure that's you're using https://github.com/elixir-lsp/elixir-ls/ (vs this repo). Then if you're still having an issue file an issue there (and fill out the full issue template) and feel free to link back to this issue as an additional detail. Thanks!
