### ISSUE TITLE
Poor performance on Dialyzer

### ISSUE THREAD

**Issue by msudgh** [JakeBecker/elixir-ls#205]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Operating system: Darwin x64 19.2.0
* Client (editor or IDE): VSCode

Sometimes dialyzer isn't working correctly as end-user expect it, The following issues I encountered:

- Poor performance on integration with Extension and Dialyzer, it takes about **1s** to get the result of analyzing every time for any action involving dialyzer (Maybe **WebSocket** or equivalent realtime approaches would be a better idea)
- Caching result of analyzing

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
