### ISSUE TITLE
 how do I make @spec to print in my code? (if even possible)

### ISSUE THREAD

**Issue by houmanka** [JakeBecker/elixir-ls#211]
Hi everyone,

`@spec` is generating, how do I make it so it can print in my code? in VSCode, I used to click on it.

I can't find any keybinding for it and I am not sure what should I search for. 

Thank you for your help in advance.

![Screen Shot 2020-03-05 at 11 28 26 pm](https://user-images.githubusercontent.com/391493/75983002-cae5fa00-5f3b-11ea-8456-450764c3c33b.png)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
