### ISSUE TITLE
Issue with comments in deps list

### ISSUE THREAD

**Issue by BobbyMcWho** [JakeBecker/elixir-ls#212]
### Environment

* Elixir & Erlang versions (elixir --version): 1.8.1 & 21.2.3
* Operating system: MacOS Catalina 10.15.1
* Client (editor or IDE): VSCode using vscode-elixir-ls fork

When Adding a comment in between dependencies in the `mix.exs` file, the server throws an error and shows error squiggles all over the file:
```
an exception was raised:
    ** (Mix.Error) Can't continue due to errors on dependencies
        (mix) lib/mix.ex:375: Mix.raise/1
        (mix) lib/mix/tasks/deps.loadpaths.ex:28: Mix.Tasks.Deps.Loadpaths.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/tasks/loadpaths.ex:35: Mix.Tasks.Loadpaths.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/tasks/compile.ex:90: Mix.Tasks.Compile.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (language_server) lib/language_server/build.ex:164: ElixirLS.LanguageServer.Build.compile/0
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
