### ISSUE TITLE
Incomprehensible Dialyzer warning after erlang elixir update

### ISSUE THREAD

**Issue by theagilecoder** [JakeBecker/elixir-ls#213]
### Environment

* Elixir & Erlang versions (elixir --version):Erlang/OTP 22 Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Operating system: Ubuntu 18.04
* Client (editor or IDE): VS Code
![Screenshot from 2020-03-22 10-49-51](https://user-images.githubusercontent.com/5019222/77243143-b0469d00-6c2c-11ea-96d4-42243db3ceb5.png)

I am getting this warning after erlang elixir was updated by the OS.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
