### ISSUE TITLE
Sharing _build/deps with main project causes significant system slowdowns when running alongside Phoenix with auto reload

### ISSUE THREAD

**Issue by cblage** [JakeBecker/elixir-ls#214]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```
* Operating system: macOS Catalina 10.15.4
* Client (editor or IDE): VSCode Version: 1.44.0

Since elixir_ls shares `_build`/`deps`  with the main project for a bunch of things, whenever it decides to recompile the code (if running alongside Phoenix with autoreload) - it causes a race condition between the compiler inside Phoenix auto reload and the elixir_ls compiler. This causes significant slowdowns and sometimes warnings and errors while waiting for both to finish.

We should be able to configure it to NEVER re-use the `deps` or  `_build` directory with the main project to avoid conflicts like these

**Comment by delameko** [comment]
Hi Carlos, development has moved to [elixir-lsp/elixir-ls](https://github.com/elixir-lsp/elixir-ls).

**Comment by cblage** [comment]
Oops, thanks @delameko

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
