### ISSUE TITLE
Support textDocument/rename

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#22]
Documented here: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rename

**Comment by irrigator** [comment]
This would be super useful! How can it be done in Elixir? Anything we can help?

**Comment by JakeBecker** [comment]
My first thoughts on how to approach renaming a function:
* Use Elixir Sense's `ElixirSense.Core.Source.subject/3` to find the function at the cursor
* Use `Mix.Tasks.Xref.calls/0` to find the file and line numbers that call it
* Somehow find the actual tokens at those lines and replace them

I have no immediate plans to build this myself, so feel free to take a stab at it. You can take a look at some of the existing providers like `References` and `DocumentSymbols` to get an idea for how you might implement it.

**Comment by balduncle** [comment]
In case anyone else plans on or has already started working on this, I have started working on implementing this.

**Comment by axelson** [comment]
Updated link to the protocol section: https://microsoft.github.io/language-server-protocol/specification#textDocument_rename

**Comment by balduncle** [comment]
Thanks.  I've been referencing that and have proven out that I can get renames to work with some hardcoded values.  For function renames I'm using the references provider to lookup references and need to add the definition to the list, and then add the extra step of determining the start and end characters on the specified lines, since references just positions us at character 0.

**Comment by balduncle** [comment]
I'm documenting my plans and findings at https://www.notion.so/balduncle/Project-ElixirLS-Rename-Support-aad15b35d4a54d2897df93c713191a99.  Any input is welcome.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
