### ISSUE TITLE
Release prebuild .ez packages

### ISSUE THREAD

**Issue by hauleth** [JakeBecker/elixir-ls#25]
This would greatly simplify deployment and integration of application plugins instead of requiring each one to build project from source.

**EDIT:**

To clarify. The idea isn't that we should provide `.ez` files to install it using `mix archive.install` but for fetching prebuild tool instead compiling it each time. To prevent people from "accidentally" installing it using `mix archive.install` it could be released as one archive that would need to be downloaded and extracted separately.

This could even be done on CI for each signed tag build which would mark new release. This would provide much simpler versioning and installation. This is especially useful for people using older versions of Elixir without need to install `1.6.0-dev` version.

**Comment by michalmuskala** [comment]
An alternative would be to release the server on hex, then it could be installed with

```
mix archive.install hex elixir-ls
```

**Comment by JakeBecker** [comment]
The difficulty with packaging it as an escript is that a typical escript embeds Elixir so the script runs with whatever Elixir version it was packaged with. That's good for most scripts, but with ElixirLS it's nice to use the system Elixir installation. I used to package ElixirLS as an escript in the VS Code plugin, but it needed additional shell or batch scripts to find the system Elixir installation and set `ERL_LIBS`, and I had trouble making this reliable (especially on Windows). If there were an easy way to run an escript using the system Elixir version, I think that'd be a good option.

**Comment by JakeBecker** [comment]
I've finally gotten around to this. You can download a precompiled release now: https://github.com/JakeBecker/elixir-ls/releases

It includes launcher `.sh` and `.bat` scripts which should hopefully make it easier to integrate into plugins.
