### ISSUE TITLE
Add Elixir-ls to langserver.org

### ISSUE THREAD

**Issue by johnhamelink** [JakeBecker/elixir-ls#26]
Hey there,

I was reading through [langserver.org](https://langserver.org/) and noticed elixir-ls is missing from the list. I thought it'd be a good idea to add elixir-ls to the list! The only reason why I haven't done it myself is I'm not sure what has and hasn't been implemented yet.

**Comment by irrigator** [comment]
It's already there!
<img width="730" alt="screen shot 2018-02-02 at 11 02 07 am" src="https://user-images.githubusercontent.com/9542232/35714578-8b2673c2-0808-11e8-96f2-20b559f3890e.png">

**Comment by chulkilee** [comment]
langserver/langserver.github.io#81
