### ISSUE TITLE
Plans to build an Elixir LanguageServer Client?

### ISSUE THREAD

**Issue by clintgibler** [JakeBecker/elixir-ls#37]
Thanks for all of your hard work in making this and [vscode-elixir-ls](https://github.com/JakeBecker/vscode-elixir-ls), this is great work!

Do you have any plans to build a LanguageServer client written in Elixir?

I'm working on an Elixir side project where it'd be really useful to be able to communicate with this or other language servers. There doesn't appear to be many LSP clients (see [here](https://langserver.org/)) and I think people would find this useful. I'm not totally sure, but I believe the client VSCode uses is in [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node/tree/7216a88a8b26f91889a3633ee10375935a03b60d/client).

If not, no problem, I was just curious. Thanks!

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
