### ISSUE TITLE
Provide tagged releases

### ISSUE THREAD

**Issue by the-kenny** [JakeBecker/elixir-ls#44]
Neither `elixir-ls` nor `elixir-vscode-ls` have tagged releases. It would be much easier to coordinate which version of both projects is working fine with the other if the git commits would be tagged accordingly.

**Comment by JakeBecker** [comment]
I've just gotten around to publishing a tagged release for ElixirLS:  https://github.com/JakeBecker/elixir-ls/releases . The .zip includes launcher `.sh` and `.bat` scripts which should hopefully make it easier to integrate into plugins.

As for the VS Code extension, I probably ought to use Git tags for those releases too. The canonical version number for that is what's in `package.json`.
