### ISSUE TITLE
ExUnit configuration is ignored in the debug task

### ISSUE THREAD

**Issue by michallepicki** [JakeBecker/elixir-ls#46]
I have a few lines in `test_helper.exs` which set configuration to ExUnit, such as setting a formatter or excluding tests, for example:
```
ExUnit.configure(
  exclude: [external_api: true]
)
```
Unfortunately, this configuration seems to be ignored when running tests through VSCode with the default `launch.json` contents (like in the README.md).

PS: I was not sure whether this issue belongs here or in the VSCode extension repo.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
