### ISSUE TITLE
"Restart" button non functional for vs code debugger

### ISSUE THREAD

**Issue by cevn** [JakeBecker/elixir-ls#47]

**Comment by chulkilee** [comment]
Any more details? Probably this should be in https://github.com/JakeBecker/vscode-elixir-ls

**Comment by JakeBecker** [comment]
I can reproduce this, and it's fine to leave the issue on this repo. I really don't know what's causing it, though. According to the protocol docs, by setting the capability `supportsRestartRequest` to `false`, VS Code should handle the restart button itself by restarting the debug adapter: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L362

**Comment by JakeBecker** [comment]
Fixed it! https://github.com/JakeBecker/elixir-ls/commit/8774d406908203905af7f8afa4787fa72b996202

The server was terminating before responding to the `disconnect` request, and I guess that confused the client. Now it terminates after responding and the restart button works. Update to v0.2.12 in VS Code and give it a try.
