### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by kodburn** [JakeBecker/elixir-ls#48]
I use elixir-ls in VS Code and the autocomplete functionality is missing. 
Other features like debugging, dializer, go-to work as expected.

**Comment by JakeBecker** [comment]
It should only trigger automatically if you type a module name followed by a period, like `IO.`. Does this bring up any suggestions?

**Comment by kodburn** [comment]
Yeah, it does work. Sorry for not reading changelog first 😄

**Comment by kodburn** [comment]
Is there a way to enable autocomplete of variables, methods etc.?

**Comment by kodburn** [comment]
One more thing I noticed is that when `elixir-ls` is enabled, VS Code's autosuggestions stop working.
Same goes for `vscode-elixir` plugin, it's not working when along with `elixir-ls`.

**Comment by JakeBecker** [comment]
`Ctrl + Space` triggers autocomplete manually. You may want to enable `editor.quickSuggestions` in your settings to restore the default continuous autocompletion behavior.
