### ISSUE TITLE
Extension is not starting

### ISSUE THREAD

**Issue by sammkj** [JakeBecker/elixir-ls#51]
Usually when I go to Output pane, I will see an ElixirLS task and `.elixir_ls` will be generated. But after updating to the newest version, extension does not seem to start. What can I do to debug this?

**Comment by JakeBecker** [comment]
Try downloading the `elixir-ls.zip` [here](https://github.com/JakeBecker/elixir-ls/releases) and extract it, then try running `language_server.sh` (or `.bat` on Windows) from a terminal. If that fails, hopefully it'll give a more informative error. If it works, I probably should add better logging to the extension so we can figure out what's going on when it fails to launch.

**Comment by JakeBecker** [comment]
Oh, also check the dev console (`Help > Toggle Developer Tools`)

**Comment by sammkj** [comment]
So I downloaded and extracted the folder.

In terminal, I did:

```bash
sammkj@sammkj:~/Downloads$ chmod 777 language_server.sh
sammkj@sammkj:~/Downloads$ ./language_server.sh
Content-Length: 101

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS\n","type":4}}
```

Then in devtool, I saw some errors when I tried to save `.ex` file.

![image](https://user-images.githubusercontent.com/9153498/36634208-006d949a-196f-11e8-8d95-d125023f618c.png)

**Comment by JakeBecker** [comment]
Okay, try this: `git clone --recursive git@github.com:JakeBecker/vscode-elixir-ls.git`

Then open that project in VS Code and run the "Launch Extension" debug configuration. If everything goes wrong, it should break when it gets a message from the server and you can see what it is here:
<img width="296" alt="screen shot 2018-02-24 at 11 50 31 am" src="https://user-images.githubusercontent.com/547940/36634416-3bff1616-1959-11e8-8720-792127198cb7.png">

Hopefully we'll be able to see what the server's sending that's messing things up.

**Comment by sammkj** [comment]
Okay.

Here's what I did:

```bash
git clone --recursive https://github.com/JakeBecker/vscode-elixir-ls.git
cd vscode-elixir-ls
yarn install
cd elixir-ls
mix deps.get
```

Then I opened the folder with VS Code and tried to debug it, saw nothing in any of the panels. :thinking:

**Comment by sammkj** [comment]
I even uninstalled and re-installed VS Code. No difference noted.

**Comment by JakeBecker** [comment]
Open the parent folder, `vscode-elixir-ls`. It should have debug configurations already.

**Comment by sammkj** [comment]
yeap. that's what I did.

**Comment by JakeBecker** [comment]
In the VS Code window it launches, you need to open an Elixir project and open an elixir source file. That should launch the language server, which should then crash and you can debug the exception in the original VS Code window.

**Comment by sammkj** [comment]
Ok. I disabled all my extensions to make things clean as possible. But I'm getting a different error:

```
Exception has occurred: Error
Error: Cannot find module '/usr/share/code/resources/app/node_modules/spdlog/build/spdlog.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/share/code/resources/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/spdlog/index.js:3:35)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/spdlog/index.js:21:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

![image](https://user-images.githubusercontent.com/9153498/36636254-d4f5630c-1990-11e8-8c9e-563f703c605c.png)

**Comment by sammkj** [comment]
So apparently this `Logger.debug("Disabling Timber logger")` in `config/config.ex` is causing problem.

**Comment by JakeBecker** [comment]
Now I'm intrigued!

Try creating a new, empty Mix project and see if the language server launches on that. If it does, please post a mix project somewhere that reproduces the error so I can check it out.

**Comment by fkumro** [comment]
Looks like I reported the same issue in the wrong repo: https://github.com/JakeBecker/vscode-elixir-ls/issues/43

**Comment by JakeBecker** [comment]
@fkumro Thanks for posting that project, I can reproduce the problem on it. I'm looking into it.

**Comment by JakeBecker** [comment]
Okay, I've figured out the problem.

The first thing ElixirLS does when it launches is replace the built-in process for stdout with another process that wraps any output with a `window/logMessage` JSON message. But before Mix even launches the language server task, it loads the mixfile from the current folder, so if there's any print statements in the mixfile, it will print those without wrapping them.

I'm working on a fix.

**Comment by fkumro** [comment]
Excellent! I was also thinking what may have changed between my environments. I ended up upgrading to Nerves 1.0.0-rc.1 which may have changed what is sent to stdout. That would explain the timing of receiving the issue on my end.

**Comment by JakeBecker** [comment]
I'll do a release sometime in the next week or so with this fix, but for now, you can comment out any print or log calls in your mixfile.

**Comment by JakeBecker** [comment]
The latest release of the VS Code extension (v0.2.13) should fix this. Give it a try!

**Comment by fkumro** [comment]
![elixir-ls-error-dev-tools](https://user-images.githubusercontent.com/51793/36938724-e55d476a-1ef3-11e8-8d01-0a2fe8ac116f.png)

Unfortunately I receive this error now, it happens if I have the `Mix.shell().info` line comment out and not commented out.

**Comment by JakeBecker** [comment]
Ah... @fkumro, your "lake_effect" project is actually a good test case because of how complicated its setup is. I was able to reproduce the error and I think I've fixed it in a release I've just published (v0.2.14).

In the previous fix, I was able to have Mix avoid loading the project's mixfile until we've started intercepting stdout. But it would still try to load the config files, and in your project, that fails if the mixfile hasn't been loaded.

I've revised the way the server is launched now and it seems to fix it on your project. Please update and give it a try.

**Comment by fkumro** [comment]
Tested the latest release (v0.2.14) with my previous change removed. Works like a charm @JakeBecker, thanks!!

**Comment by mvalitov** [comment]
I now faced the same problem. When running, vscode writes "Failed to run 'elixir' command. ElixirLS will probably fail to launch. Logged PATH to Development console".
In the console, I see:
```
[Error - 11:59:44] Connection to server is erroring. Shutting down server.
[Error - 11:59:44] Connection to server is erroring. Shutting down server.
/home/mvalitov/.vscode-oss/extensions/jakebecker.elixir-ls-0.2.23/elixir-ls-release/language_server.sh: line 18: elixir: command not found
```

but if you print the version:
```
elixir -v
Erlang / OTP 21 [erts-10.0.8] [source] [64-bit] [smp: 8: 8] [ds: 8: 8: 10] [async-threads: 1] [hipe]

Elixir 1.6.6 (compiled with OTP 19)
```

versions:
Linux mvalitov-pc 4.18.12-1-MANJARO #1 SMP PREEMPT Fri Oct 5 16:06:16 UTC 2018 x86_64 GNU/Linux
![image](https://user-images.githubusercontent.com/8917265/46658469-72ca8d00-cbbb-11e8-9ee7-8761b84adb7b.png)
