### ISSUE TITLE
Support Find References in umbrella apps

### ISSUE THREAD

**Issue by mattbaker** [JakeBecker/elixir-ls#55]
Right now Find References only works for non-umbrella applications. More context can be found in the discussion on https://github.com/JakeBecker/elixir-ls/pull/50 (towards the bottom).

One idea: have find references and the build process share a lock so that find-refs can't occur during the compilation process.

**Comment by mattbaker** [comment]
We probably want to pass the include_siblings option to `calls/0`?
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/xref.ex#L116

**Comment by mattbaker** [comment]
Quick hack running xref under each application. Had to override the build path and fiddle with file paths (which makes sense):
https://github.com/mattbaker/elixir-ls/commit/f568917f41cc9b14369e3cb5d01737a2cda7e888

**Comment by JakeBecker** [comment]
Left a couple comments, but the approach looks good. 👍 on adding a lock that compilation and find-references will share.

**Comment by mattbaker** [comment]
Awesome, I'll keep pluggin away. Thanks for the feedback, I'll integrate that too.
