### ISSUE TITLE
Support for elixir_sense macro expansion feature?

### ISSUE THREAD

**Issue by Trevoke** [JakeBecker/elixir-ls#60]
Hi there,

I'm trying to reformat alchemist.el to use elixir-ls, and I see that elixir_sense has a feature that alchemist.el would like, which is a macro expansion ( https://github.com/msaraiva/elixir_sense#credits ). 

I realize that feature is not generic enough to be supported by LSP, but alchemist.el would definitely have a use for it.

Unfortunately elixir_sense has zero documentation, so I don't know how that expand feature is supposed to work, but it seems like you've done all the work of figuring that out already, so I figured I might be able to stand on your shoulders for that one.

I'd be happy to write the client-side query for it.. But I have no idea what it's supposed to be :/

**Comment by JakeBecker** [comment]
ElixirLS doesn't use the request-based API provided by Elixir Sense, it just calls the functions directly. The request format for macro expansion appears to be here: https://github.com/msaraiva/elixir_sense/blob/master/lib/elixir_sense/server/request_handler.ex#L29

Better to ping @msaraiva than me for future questions though :)

**Comment by msaraiva** [comment]
> Unfortunately elixir_sense has zero documentation

@Trevoke Have you tried this?
https://hexdocs.pm/elixir_sense/ElixirSense.html

Googling `elixir_sense documentation`, it's the second link, right after the project's github page. 

You could also take a look at the unit tests:
https://github.com/msaraiva/elixir_sense/blob/master/test/elixir_sense/eval_test.exs#L43

**Comment by Trevoke** [comment]
@JakeBecker I'm trying to figure out how the LSP works and what kind of request elixir-ls can accept / where to make changes to elixir-ls so that it can receive a request for macro expansion for the client.

The documentation for LSP's kind of a slow slog, do you have any tips for me?
