### ISSUE TITLE
ElixirLS crashes when asked to provide pop-up documentation for GenStage

### ISSUE THREAD

**Issue by Trevoke** [JakeBecker/elixir-ls#63]
### Environment

* Elixir & Erlang versions (elixir --version): erlang 19.3.6.6 and Elixir 1.6.4
* Operating system: OSX
* Client (editor or IDE): emacs

### Crash report template

What I do:

In VsCode, I hover over the GenStage module name.

What happens:

Documentation does not appear.

1. Reproduced with most recent vscode and vscode-elixir-ls in same project
2. Reproduced Reproduced with most recent vscode and vscode-elixir-ls in empty project (just added gen_stage as dependency)
3. No errors in developer console
4. Error output from the "view > output" window:

```
[Error - 19:02:31] Request textDocument/hover failed.
  Message: Internal error: an exception was raised:
    ** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.extract_spec_ast_parts/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:227: ElixirSense.Core.Introspection.extract_spec_ast_parts({:subscription_tag, [], []})
        (elixir_sense) lib/elixir_sense/core/introspection.ex:171: ElixirSense.Core.Introspection.format_spec_ast/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:153: ElixirSense.Core.Introspection.format_type/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:133: anonymous fn/2 in ElixirSense.Core.Introspection.get_types_with_docs/1
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir_sense) lib/elixir_sense/core/introspection.ex:80: ElixirSense.Core.Introspection.get_types_md/1
        (elixir_sense) lib/elixir_sense/core/introspection.ex:30: ElixirSense.Core.Introspection.get_all_docs/1
        (elixir_sense) lib/elixir_sense/providers/docs.ex:13: ElixirSense.Providers.Docs.all/4
  Code: -32603 
[Error - 19:02:31] Process #PID<0.318.0> raised an exception
** (FunctionClauseError) no function clause matching in ElixirSense.Core.Introspection.extract_spec_ast_parts/1
    (elixir_sense) lib/elixir_sense/core/introspection.ex:227: ElixirSense.Core.Introspection.extract_spec_ast_parts({:subscription_tag, [], []})
    (elixir_sense) lib/elixir_sense/core/introspection.ex:171: ElixirSense.Core.Introspection.format_spec_ast/1
    (elixir_sense) lib/elixir_sense/core/introspection.ex:153: ElixirSense.Core.Introspection.format_type/1
    (elixir_sense) lib/elixir_sense/core/introspection.ex:133: anonymous fn/2 in ElixirSense.Core.Introspection.get_types_with_docs/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir_sense) lib/elixir_sense/core/introspection.ex:80: ElixirSense.Core.Introspection.get_types_md/1
    (elixir_sense) lib/elixir_sense/core/introspection.ex:30: ElixirSense.Core.Introspection.get_all_docs/1
    (elixir_sense) lib/elixir_sense/providers/docs.ex:13: ElixirSense.Providers.Docs.all/4
```

**Comment by JakeBecker** [comment]
The on-hover documentation produces frequent errors, unfortunately. I've mostly been able to ignore them because they don't impact the usability of the VS Code extension much, since the server can continue even if a request handler returns an error. I set the VS Code extension to not highlight the output pane on errors, so users typically won't notice them.

Really, though, I should probably just fix it, but in the meantime, how does the Emacs client handle errors like this? If the errors could be made unobtrusive, that might be an okay stopgap for now.

**Comment by Trevoke** [comment]
Right now it's fairly obtrusive unfortunately, the stacktrace shows up in the messaging area at the bottom (which is, I think, the equivalent of the "output" tab in the vscode).

To which extent is this a problem with elixir-ls and to which extent is it a problem with elixir_sense?

**Comment by lukaszsamson** [comment]
I'm no longer able to reproduce this crash. It was most likely fixed along with similar ones in https://github.com/msaraiva/elixir_sense/issues/32

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
