### ISSUE TITLE
Disable code completion for default params

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#64]
_From @quolpr on March 12, 2018 8:29_

Is it possible to disable code completion for default params? For example, when I auto complete this:

```
Repo.delete_
```

It comes to this:

```
Repo.delete_all(queryable, opts \\ [])
```

But in almost all cases I don't want touch the default values

_Copied from original issue: JakeBecker/vscode-elixir-ls#56_

**Comment by JakeBecker** [comment]
Agreed, the current way of handling these is not ideal. Better, I think would be to have multiple suggestions and prioritize the ones without default params above the ones with them.

**Comment by akash-akya** [comment]
We can split the functions with default arguments into multiple functions by removing default arguments. And prioritizing functions with the least arguments first. Currently I have working crude version of this implemented in my elixir_sense fork https://github.com/akash-akya/elixir_sense. 

It seems that the upstream is not actively maintained, so it might just stay in my fork.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
