### ISSUE TITLE
Path mapping to support "Go to definition" inside Docker

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#65]
_From @iJackUA on June 15, 2017 9:35_

Hi, this Extension and ElixirLS by itself looks very promising!

Previously I have started the same topic in VSCode-Elixir extension repo https://github.com/fr1zle/vscode-elixir/issues/59  (all details and my temporary solution is there).

Briefly: 
Is it possible somehow to specify path mapping between container FS and Host FS? (I suppose it should be a Workspace settings per project like mapping "${workspaceRoot} => /www")
Because when you develop locally using Docker containers, so Erlang/Elixir by itself and the source code are placed INSIDE the container. 
And `module.module_info[:compile][:source]` returns absolute path for container FS, but not for Host FS (that is expected by VSCode).
I suppose the same issue would arise not only for "go to definition" but for Debugger call stack source code display also.

I have a small repo with steps and expected / actual behavior https://github.com/iJackUA/vscode-elixir-docker-test

As I see this issue should be solved on both parts: VSCode extension should have path mapping param and pass it to Elixir server to do path normalization where `module_info` is done.

I understand that my request is not the main priority at such an early dev stage, but if you could just keep in mind this use case and eventually provide a solution for this - it would be awesome!

_Copied from original issue: JakeBecker/vscode-elixir-ls#7_

**Comment by gilles-bertrand** [comment]
This feature would be great on vagrant too

**Comment by barkerja** [comment]
This is actually related to an issue I am having with Docker and my Elixir projects that leads me to ask: should the build artifacts be synced between host and container? Doesn't this lead to cross-compile issues?

I have been (trying) to use named volumes to prevent the `_build` folder from syncing between host and container; I find that every time VSCode-ElixirLS recompiles my application, it causes all kinds of issues for the running application inside Docker.

**Comment by brkattk** [comment]
I've also been using named volumes for `_build` and also `deps`, since NIFs like with bcrypt are different across hosts. ElixirLS seems to cause issues regardless

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
