### ISSUE TITLE
Format on save does not respect imported formatter configuration

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#67]
_From @Rosetjau on March 16, 2018 13:58_

When running the formatter from command line via `mix format` the formatter respects the configuration that is imported from dependencies. The same does not seem to apply to the "format on save" feature in Visual Studio Code.

I have set up an [example repository](https://github.com/Rosetjau/elixir_ls_format_on_save) to reproduce this issue. Steps to reproduce:

1. Clone the repo
2. Run `mix format` from command line. Notice that the formatter exits without changing the `schema.ex` file, because the `.formatter.exs` file imports the configuration that is exported by Absinthe
3. Open the project with Visual Studio Code, edit the workspace settings to enable "editor.formatOnSave", open the `schema.ex` file and save it
4. Upon saving the file the formatter will add parentheses to the `schema.ex` file, even if the Absinthe formatter configuration declares those functions/macros as locals_without_parens

_Copied from original issue: JakeBecker/vscode-elixir-ls#58_

**Comment by JakeBecker** [comment]
Ah, looks like they've added a lot of configuration options to the format task since I added support for it to ElixirLS. Unfortunately, supporting those features right now will likely involve copy-and-pasting a lot of private functions from Elixir. I'm willing to do that, but I think I also will send a PR to try to export some of the configuration functionality from `Mix.Tasks.Format` in future Elixir versions.

I'll likely get to this sometime next week.

**Comment by JakeBecker** [comment]
I added a new function to `Mix.Tasks.Format` to return formatter options for a given file, which should fix this. I'll likely do a release tomorrow with the fix and I'll comment here once it's out.

You'll need to be running the latest (pre-release) version of Elixir for it to work, though. You can install it with `kiex` by running `kiex install master`.

**Comment by Rosetjau** [comment]
Thank you :+1:

**Comment by JakeBecker** [comment]
Just published a release with the fix.

**Comment by hickscorp** [comment]
I would suggest to re-open this issue. We are seeing an non-reproducible problem upon saving.
*sometimes* the formatter rules are ignored. `Ctrl + Z` cancels those bad changes. Sometimes it is honored...

**Comment by a-kinder** [comment]
^ seconded, seems to ignore `locals_without_parens` as mentioned in https://github.com/JakeBecker/vscode-elixir-ls/issues/21

**Comment by hickscorp** [comment]
It's definetely adding parenthesis randomly upon saving (sometimes yes, sometimes not).

**Comment by zachdaniel** [comment]
I'm also seeing this issue (on the latest version)

**Comment by zachdaniel** [comment]
(still)

**Comment by axelson** [comment]
@zachdaniel Issues should be filed on the new repo (https://github.com/elixir-lsp/elixir-ls/). Although this one sounds like a duplicate of https://github.com/elixir-lsp/elixir-ls/issues/402
