### ISSUE TITLE
Log folder showing up in projects

### ISSUE THREAD

**Issue by Eptis** [JakeBecker/elixir-ls#69]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.4, 20.1
* Operating system: OSX 10.12.6
* Client (editor or IDE): Visual Studio Code

## Problem:

Since the last update I believe I see a `log/` folder popping up with IEx logs whenever I run an IEx session.

- Why is this folder here?
- Is there a way to turn this off?

**Comment by JakeBecker** [comment]
Are you running IEx from the command-line or from VS Code somehow? I can't think of a way this would be caused by ElixirLS.

**Comment by Eptis** [comment]
Hmmm I thought it was the elixir ls plugin because after disabling it the folder didn't reappear. Now I'm not sure... I'll have a second look, but indeed it is probably not elixir ls related
