### ISSUE TITLE
elixirLS settings not working in workspace settings

### ISSUE THREAD

**Issue by jerrett** [JakeBecker/elixir-ls#74]
### Environment

Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.4 (compiled with OTP 19)
Ubuntu / VS Code
------------------

elixirLS.dialyzerEnabled (and dialyzerWarnOpts) settings work in my user settings, but if i set them in "workspace settings" they aren't picked up (VSCode shows a (i) icon, doesn't apply them, and doesn't syntax highlight them)

:(

**Comment by JakeBecker** [comment]
Can you post a screenshot?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
