### ISSUE TITLE
language server should be able to fufill requests even without textdocument/didOpen Notifications

### ISSUE THREAD

**Issue by ggilmore** [JakeBecker/elixir-ls#75]
The [LSP Spec says the following](https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen): 

> ... Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed.

For example, I see no hover when I hover over `puts` in this file: https://github.com/philnash/elixir-examples/blob/HEAD/hello-world/hello-world.exs#L1, unless I manually make my client send this `didOpen` notification with the file contents. The spec says that language servers should still be able to hovers, etc. even without this notification.

**Comment by JakeBecker** [comment]
Huh. I guess it should be possible to implement that, but what's the actual use case for it? It seems like it shouldn't be possibly to do a hover on a file that isn't open... Are you using a client that doesn't send the `didOpen` notifications?

**Comment by ggilmore** [comment]
Yep - I'm experimenting with adding basic Elixir support for https://about.sourcegraph.com/ via https://github.com/sourcegraph/lsp-adapter (more on this soon :) ). 

We use language servers to power our code intelligence features. We don't send `didOpen` notifications because they don't make sense in a read-only context.

**Comment by JakeBecker** [comment]
Oh, neat! I see there's a hack suggested in the readme for this situation: https://github.com/sourcegraph/lsp-adapter#did-open-hack

**Comment by ggilmore** [comment]
Yep! (I'm the one that wrote that) We'd love to be able to be able to use this language server without needing the hack, and it'd let other clients that don't send the `didOpen` notification to benefit as well

**Comment by ggilmore** [comment]
A rough preview of it in action can be seen here, if you're interested: https://github.com/sourcegraph/lsp-adapter/pull/27

**Comment by JakeBecker** [comment]
Very cool. I've not been spending much time on ElixirLS lately, but it's in my backlog. If you want to take a stab at it yourself, I'm happy to review a PR that implements it.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
