### ISSUE TITLE
ElixirLs not reporting Syntax Errors/Warning

### ISSUE THREAD

**Issue by heron-exactaworks** [JakeBecker/elixir-ls#77]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 19)
```
* Operating system: Ubuntu 18.4
* Client (editor or IDE): VS Code Insiders

`example.ex`
```elixir
handle_open = fn
  {:ok, file} -> "First line #{IO.read(file, :line)}"
  {_, error} -> "Error #{:file.format_error(error)}"


IO.puts(handle_open.(File.open("hello_world.txt")))

IO.puts(handle_open.(File.open("notfound.txt")))
```

Aparently the ElixirLS server is catching the error, but its not highlighting the line/file on VsCode.
ElixirLS View -> Output Log:
```
[Error - 11:19:51 AM] Request textDocument/formatting failed.
  Message: Internal error: an exception was raised:
    ** (TokenMissingError) nofile:9: missing terminator: ) (for "(" starting at line 8)
        (elixir) lib/code.ex:442: Code.format_string!/2
        (language_server) lib/language_server/providers/formatting.ex:12: ElixirLS.LanguageServer.Providers.Formatting.format/3
        (language_server) lib/language_server/server.ex:415: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32603 
```

**Comment by OvermindDL1** [comment]
Just as another test thing, doesn't seem like an elixir-ls issue but rather an issue with the vscode thing as it is working properly in Atom.

**Comment by JakeBecker** [comment]
Is this file in a Mix project? ElixirLS runs the `mix compile` task to get any errors, so if this file isn't inside `lib` in a Mix project, errors won't be shown.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
