### ISSUE TITLE
Just letting you know I've started a fork

### ISSUE THREAD

**Issue by Trevoke** [JakeBecker/elixir-ls#78]
Hi,

I've started [a fork](https://github.com/elixir-lsp/elixir-ls) of this project with the goal of providing complete support for [alchemist.el](https://github.com/tonini/alchemist.el/pull/341) and, by extension, other LSP clients.

I look forward to coordinating on contributions, in case you intend to pursue upkeep and/or development of this project. If you're uninterested, please let me know whether you care about the name staying the same or being changed. 

Thank you.

**Comment by axelson** [comment]
We've now merged a number of PR's on this fork, although there's still more to do before it's in a better state.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
