### ISSUE TITLE
Incremental dialyzer does not catch changes in remote types that fix a warning.

### ISSUE THREAD

**Issue by JakeBecker** [JakeBecker/elixir-ls#79]
_From @NobbZ on May 17, 2018 21:4_

Given the files `a.ex` and `b.ex`, where in `b.ex` a type from `a.ex` is used in a spec.

But then there is a warning in because I am not using the type correctly. Therefore I alter the type defined in `a.ex`.

The warning in `b.ex` will persist until I `rm -rf .elixir_ls/dialyzer_*` and reload VScode.

start with

```
# a.ex
defmodule A do
  @type t :: %{}
end

# b.ex
defmodule B do
  @spec doit(A.t()) :: A.t()
  def doit(a), do: %{a | ok: true}
end
```

Get a warning at `B.doit/1`s `@spec`.

Fix `a.ex`:

```
defmodule A do
  @type t :: map()
end
```

But the warning in b.ex persists, even after restarts of VScode.

_Copied from original issue: JakeBecker/vscode-elixir-ls#72_

**Comment by ckruse** [comment]
changing the corresponding file and thus forcing a recompile works as well

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
