### ISSUE TITLE
elixir-ls requires elixir sources

### ISSUE THREAD

**Issue by NobbZ** [JakeBecker/elixir-ls#8]
According to what I discovered in JakeBecker/vscode-elixir-ls#4, it seems as if elixir-ls (currently) strictly requires availability of the sourcecode of elixirs libraries.

This should be mentioned in the installation instructions, or even better, make it use the `*.beam` files if onyly those are available.

**Comment by JakeBecker** [comment]
So far, I've been unable to reproduce this. Sources should only be required for doing go-to-definition on source files. Please re-open if you're able to reproduce this using the latest version in VS Code. Thank you!
