### ISSUE TITLE
Breakpoints not hit in VSCode except using "Test Configuration"

### ISSUE THREAD

**Issue by mtancock** [JakeBecker/elixir-ls#81]
This seems to be similar to #39 (which was closed)

I have the default configurations. If I run the "test" config, I hit breakpoints which have been set, however running the default mix task _doesn't_.

My config:

``` {
    "version": "0.2.0",
    "configurations": [
      {
        "type": "mix_task",
        "name": "mix (Default task)",
        "request": "launch",
        "projectDir": "${workspaceRoot}"
      },
      {
        "type": "mix_task",
        "name": "mix test",
        "request": "launch",
        "task": "test",
        "taskArgs": [
          "--trace"
        ],
        "projectDir": "${workspaceRoot}",
        "requireFiles": [
          "test/**/test_helper.exs",
          "test/**/*_test.exs"
        ]
      }
    ]
  } 
```

### Environment

* Elixir & Erlang versions (elixir --version): 1.65 (OTP 20)
* Operating system: MacOS 10.13.4
* Client (editor or IDE): VSCode 1.23.1

**Comment by JakeBecker** [comment]
Is this a phoenix project by any chance? The default task for phoenix does not launch the server, you have to add `"task": "phx.server"`.

If not, please post a repo that reproduces this and the line the breakpoint should be on.

**Comment by mtancock** [comment]
Not a phoenix project, no.

I think I'm misunderstanding things (new to Elixir). I was trying it on a new project generated by `mix new project` but that doesn't configure the mix.exs file / main module to "run", which I think is the problem. If I add in the module & implement `start()` in the main module, then I think I get break points working. So I'll close this!
