### ISSUE TITLE
'(Enum.EmptyError) empty error' in new umbrella projects on Mac OS X

### ISSUE THREAD

**Issue by bcalco** [JakeBecker/elixir-ls#82]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang 20 (erts-9.3.2), Elixir 1.6.5
* Operating system: Mac OS X High Sierra
* Client (editor or IDE): VS Code

### Problem

When opening VS Code at the root of a new umbrella project (created with `mix new PROJECT_NAME --umbrella`, the mix.exs file at the root of the new project reports the following error:

```
an exception was raised:
    ** (Enum.EmptyError) empty error
        (elixir) lib/enum.ex:1843: Enum.reduce/2
        (mix) lib/mix/tasks/compile.ex:93: Mix.Tasks.Compile.run/1
        (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
        (language_server) lib/language_server/build.ex:162: ElixirLS.LanguageServer.Build.compile/0
        (language_server) lib/language_server/build.ex:22: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (stdlib) timer.erl:166: :timer.tc/1
        (language_server) lib/language_server/build.ex:13: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (kernel) global.erl:430: :global.trans/4
```

I haven't any idea what to do to make this error go away. Apps added to the `apps` directory do not seem to have this issue, nor does it appear to affect behavior of the umbrella project or its apps. However, the flashing red underscores on every line in the file and constant reminder of an error is visually distracting.

Steps to reproduce:

```
mix new sample_umbrella_app --umbrella
cd sample_umbrella_app
code .
```

Now you'll see the mix.exs file is RED, and every line is underlined red.

<img width="1314" alt="elixirls-error" src="https://user-images.githubusercontent.com/14943929/41191750-f353088a-6bc1-11e8-8a5f-373a1a3c96cb.png">

**Comment by JakeBecker** [comment]
I couldn't reproduce this with Elixir 1.7.3 -- perhaps recent changes to Elixir fixed it? Is it still reproducible for you with the latest Elixir?

**Comment by bcalco** [comment]
> I couldn't reproduce this with Elixir 1.7.3 -- perhaps recent changes to Elixir fixed it? Is it still reproducible for you with the latest Elixir?

I will see if the latest version behaves better.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
