### ISSUE TITLE
New Dialyxir v1.0 pretty printing support?

### ISSUE THREAD

**Issue by tmepple** [JakeBecker/elixir-ls#83]
I was wondering if it is possible somehow to integrate the new "pretty print" capabilities of https://github.com/jeremyjh/dialyxir v1.0 so the IDE warnings would appear in formatted Elixir syntax instead of Erlang?

I'm not sure if it's (easily) possible since I think `elixir-ls` calls `:dialyzer` directly and doesn't interface with `dialyxir`.  I'm really not sure the integration between them but it would be great if this was possible.  Thanks!

**Comment by JakeBecker** [comment]
I gave it a try, it was pretty easy to integrate: https://github.com/JakeBecker/elixir-ls/pull/84

However, after playing with it, I'm not sure it's mature enough yet. I think I will wait for Dialyxir to fully hit 1.0 and then add an option to enable it.

**Comment by tmepple** [comment]
Wow, that was fast... thanks.  Very glad to see the integration wasn't too difficult.

Makes total sense to wait until Dialyxir v1.0 is released (no longer a RC) then enable it with an option.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
