### ISSUE TITLE
Take .formatter.exs into account when autocompleting

### ISSUE THREAD

**Issue by JohnnyCrazy** [JakeBecker/elixir-ls#89]
### Feature Request

Since the `.formatter.exs` file is now officially suported, I wonder if the autocompletion should also take it into account. For example, when autocompleting a function which is mentioned in `locals_without_parens `, it should automatically strip the parens. Because if not, the formatter will not strip them and you have to do it manually which is a pain.

This issue could also be opened in elixir_sense, but I wanted to hear your opinion on it first 👍 I could also go for a PR if you aggree.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
