### ISSUE TITLE
High latency filesystem breaks LS

### ISSUE THREAD

**Issue by NobbZ** [JakeBecker/elixir-ls#9]
I'm working on a project from my mobile workstation. Since it is my personal laptop and the projects content confidential, my boss and me came to the conclusion I shouldn't save it locally. Therefore I do use SSHFS to mount the project into my local filesystem. In general this works pretty well, but ElixirLS crashes constantly because the filesystem is taking longer than expected.

Is it possible to either increase filesystem timeouts or to start LS on a remote system and use it locally?

**Comment by JakeBecker** [comment]
Please check whether this is reproducible in the latest release. If so, please add the information from this template: https://github.com/JakeBecker/elixir-ls/blob/master/ISSUE_TEMPLATE.md

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
