### ISSUE TITLE
Information on how to configure without an IDE

### ISSUE THREAD

**Issue by archSeer** [JakeBecker/elixir-ls#91]
I'm using vim with [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and I have to configure things by hand, so there's no "settings.json".

On some projects, I don't want to run dialyzer (what I ran into: running laptop on batteries, the initial dialyzer run takes up about 40-45mins + ~85% of my entire battery, forgot to pre-run dialyzer at home), but I wasn't able to figure out how to disable it (-> ran out of power). Do I put a settings.json inside the project root? or <project-root>/.elixir-ls, etc.

**Comment by JakeBecker** [comment]
It looks like vim-lsp does support the `workspace/didChangeConfiguration` request, which is how settings get synced with the server: https://github.com/prabirshrestha/vim-lsp/blob/96b81a5880b6b91e6e5b1f6b4662e6e5da6943d9/autoload/lsp.vim#L381

I'm not very familiar with how vim/neovim plugins work, but it looks like there should be a `server_info` config somewhere where you can add a `workspace_config` key which is the equivalent of `settings.json` in VS Code. In there, you should be able to add `dialyzerEnabled: false` to disable Dialyzer.

**Comment by archSeer** [comment]
Ah so it appears that I [should have read the vim-lsp manual](https://github.com/prabirshrestha/vim-lsp/blob/96b81a5880b6b91e6e5b1f6b4662e6e5da6943d9/doc/vim-lsp.txt#L250)...

```
'workspace_config': {'dialyzerEnabled': v:false}
```

Sorry for the trouble! I'll go ahead and say thank you for your work on elixir-ls! 🎊 I've used Alchemist.vim in the past, but have been using elixir-ls since it's initial announcement :)

**Comment by megalithic** [comment]
@archSeer have you had issues with that setting (for workspace_config), elixirLS, and vim-lsp where beam.smp goes bonkers and pegs the CPU nonstop?

here's my vim-lsp entry for registering elixirLS:

```vim
  if executable($HOME.'/.elixir-ls/language_server.sh')
    au User lsp_setup call lsp#register_server({
          \ 'name': 'elixir-ls',
          \ 'cmd': {server_info->[$HOME.'/.elixir-ls/language_server.sh']},
          \ 'whitelist': ['elixir'],
          \ 'workspace_config': {'dialyzerEnabled': v:false},
          \ })
  endif
```

this ALWAYS results in beam.smp running and pegging the CPU at 100%.

however, if i run the cmd above by itself, from a prompt, everything is fine.

**Comment by archSeer** [comment]
@megalithic 

```
        \ 'workspace_config': {'elixirLS': {'dialyzerEnabled': v:false}},
```

Needs to be under the elixirLS key. It's pegging the CPU mainly because when you update OTP or Elixir versions, the whole plt file needs to be rebuilt. I got around it by typically rebuilding it in one project then copying it elsewhere.

**Comment by megalithic** [comment]
thanks tons @archSeer! that did it. :D

**Comment by zoliky** [comment]
> @archSeer have you had issues with that setting (for workspace_config), elixirLS, and vim-lsp where beam.smp goes bonkers and pegs the CPU nonstop?
> 
> here's my vim-lsp entry for registering elixirLS:
> 
> ```viml
>   if executable($HOME.'/.elixir-ls/language_server.sh')
>     au User lsp_setup call lsp#register_server({
>           \ 'name': 'elixir-ls',
>           \ 'cmd': {server_info->[&shell, &shellcmdflag, '~/.elixir-ls/language_server.sh']},
>           \ 'whitelist': ['elixir'],
>           \ 'workspace_config': {'dialyzerEnabled': v:false},
>           \ })
>   endif
> ```
> 
> this ALWAYS results in beam.smp running and pegging the CPU at 100%. i've tried it with and without the `workspace_config` option.
> 
> however, if i run the cmd above by itself, from a prompt, everything is fine.

Where do you place that? is ~/.vim/ftplugin/elixir.vim?

**Comment by megalithic** [comment]
> Where do you place that? in ~/.vim/ftplugin/elixir.vim?

i don't separate my configs, so mine is just in my main `init.vim` (i use neovim), but could easily just be in your root `.vimrc`
