### ISSUE TITLE
Recompiling inside IEX doesn't work after saving in VS Code

### ISSUE THREAD

**Issue by ewildgoose** [JakeBecker/elixir-ls#93]
### Environment

Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.6.6 (compiled with OTP 20)
OSX 10.13.15
VSCode 1.25.0

### Problem 
Hi, great plugin, but I seem to be suffering the problem described in a number of places, eg here:
https://github.com/iampeterbanjo/vscode-elixir-linter/issues/25

When saving in vscode and then issuing a recompile in iex, I simply get:

iex(1)> recompile
:noop

If I trigger a change by say saving in Sublime, then there is a recompile and reload of modified files

Based on other advice I tried to set preferences:

    "elixirLS.mixEnv": "test",
    "elixirLinter.mixEnv": "test"

However, I still don't seem to be able to force a recompile and reload in IEX. 

It's a fantastic plugin, but I'm finding this a bit of a showstopper. Does anyone have a suggestion of a workaround please?

**Comment by JakeBecker** [comment]
ElixirLS should be avoiding this issue by overriding the `build_path` to `.elixir_ls/build` (instead of the default `_build`) in the Mix project config before compilation.

Check whether the beam files in `_build` or `.elixir_ls/build` gets updated when you change a file and trigger compilation in ElixirLS. Also, are you setting the the `build_path` explicitly in your Mix project?

**Comment by JakeBecker** [comment]
Also, be aware that this problem could be caused by `elixirLinter` or even by Phoenix's live recompilation. Try disabling any other Elixir plugins for VS Code and see if it's still an issue.

**Comment by ewildgoose** [comment]
I'm so sorry... Yes, it was elixirLinter. Disabling this stopped the symptoms. 

New VSCode user here. I had incorrectly assumed that elixirLinter was getting pulled in by ElixirLs. Apologies!

As an aside, could you please point me to the code which overrides the build_path please? I wonder if I can submit a patch to the elixirLinter author to do something similar?

Thanks

**Comment by JakeBecker** [comment]
The line that does it is here: https://github.com/JakeBecker/elixir-ls/blob/master/apps/language_server/lib/language_server/build.ex#L123

It's also possible to do it with `Mix.Project.in_project/4`
