### ISSUE TITLE
Do not override editor setting for "trim trailing whitespace"

### ISSUE THREAD

**Issue by ryanhart2** [JakeBecker/elixir-ls#99]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 21, Elixir 1.7.0-rc.1
* Operating system: Ubuntu 18.04 LTS
* Client (editor or IDE): Visual Studio Code 1.25.1

The Elixir code formatter already trims trailing whitespace so it should not be necessary for the editor to do the same thing. The editor does not have the same understanding of the code semantics and can change the meaning of the code when trimming whitespace.

Example: VSCode trims trailing white-space inside multi-line strings (heredocs) whereas the Elixir code formatter does not.

See https://elixirforum.com/t/programming-elixir-chapter-13-test-issue/15348

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
